### ISSUE TITLE
Thanks for the plugin.

### ISSUE THREAD

**Issue by QAInsights** [LeeBaul/baolu-csv-data-file-config#1]
I have written an article about your plugin. Please check [it out](https://qainsights.com/allocate-test-data-to-threads-in-jmeter/).

**Comment by LeeBaul** [comment]
I read your article. Thanks for sharing.

**Comment by LeeBaul** [comment]
Later, it is planned to enhance the plug-in to support JMeter Distributed Testing.

**Comment by QAInsights** [comment]
@LeeBaul Please let me know once it is done. I can test it. Thanks!
