### ISSUE TITLE
参数化文件不支持相对路径，jmx工程文件和参数化文件同目录时只填参数化名称不能识别

### ISSUE THREAD

**Issue by zhangzhaox** [LeeBaul/baolu-csv-data-file-config#2]
![image](https://user-images.githubusercontent.com/82088551/164887487-3429d5f1-e446-4e80-850c-5b64acd650f0.png)
![image](https://user-images.githubusercontent.com/82088551/164887499-b7dbfd6b-042c-4bdf-816c-451e76cc3077.png)

**Comment by LeeBaul** [comment]
1.提供下你使用的jmeter版本
2.检查下你的脚本所在录是否包含参数化文件

**Comment by LeeBaul** [comment]
我已复现你提到的问题，我正在尝试修复此问题

**Comment by LeeBaul** [comment]
v1.2.1版本已修复此问题，你可以在工程的Download目录下载，或者自行下载构建此项目。

**Comment by LeeBaul** [comment]
我今天做了大量测试，发现在1.2.1版本并未完全解决此问题，寻找了新的解决方案
1.2.2版本已成功修复此问题。

**Comment by zhangzhaox** [comment]
感谢快速修复
